apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: application-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-demo
  template:
    metadata:
      labels:
        app: application-demo
    spec:
      containers:
      - name: application-demo
        image: ${IMAGE_REPO}:${IMAGE_TAG}
        ports:
        - containerPort: 8080
      imagePullSecrets:
        - name: kin-hk-acr
---
apiVersion: v1
kind: Service
metadata:
  name: application-demo
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: application-demo
  selector:
    app: application-demo
  type: ClusterIP

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: application-demo
  labels:
    app: application-demo
spec:
  rules:
    - host: sit.seyantszkin.xyz
      http:
        paths:
          - path: 
            backend:
              serviceName: application-demo
              servicePort: 80

